# Generated by Django 5.2.8 on 2025-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('image_search_term', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, help_text="Leave blank for a 'general' crop", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mandi', models.CharField(default='Dehradun', max_length=100)),
                ('trend', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('STABLE', 'Stable'), ('HIGH', 'High Demand')], default='STABLE', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
